name: pull request merged

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs: 
    pushed:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set jfrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              with:
                version: 'latest'

            # - name: Ping Jfrog
            #   run: |
            #     jf rt ping


            - name: read version
              id: read_version
              run: |
                version=$(cat version.txt)
                echo "version=$version" >> $GITHUB_ENV

            #ping jfrog
            - name: ping jfrog
              env: 
                JF_URL: ${{ vars.JF_URL }}
                JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
                JF_USER: ${{ secrets.JFROG_USER }}
                JF_REPO: ${{ vars.JF_REPO }}
              run: |
                version=${{ env.version }}
                jf c add --user $JF_USER --url $JF_URL --access-token $JF_ACCESS_TOKEN
                jfrog c show
                jf rt u "prcm/*" "$JF_REPO/PRCM/$version/" --flat=true --recursive=true
                # jf rt u "prcm/*" "test-spec-local/PRCM/$version/" --flat=true --recursive=true
                # jf rt u "prcm/*" "prch-config-generic-local/" --url $JF_URL --user $JF_USER --access-token $JF_ACCESS_TOKEN 