name: Pull request

on:
  pull_request:
    branches: [main, master]
    types: [opened, edited, reopened, synchronize, review_requested]
jobs:
  branch-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get version from feature branch
      id: get-feature-version
      run: |
        feature_version=$(cat version.txt)
        if ! [[ $feature_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format in version.txt. Expected format: x.y.z"
          echo "Feature version is: $feature_version"
          exit 1
        else
          echo "feature_version=$feature_version" >> $GITHUB_OUTPUT
          echo "Feature version is $feature_version"
        fi

    - name: Checkout main branch
      run: |
        git fetch origin master
        git checkout master

    - name: Get version from main branch
      id: get-main-version
      run: |
        main_version=$(cat version.txt)
        if ! [[ $main_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format: $main_version, please use format 'x.y.z'"
          exit 1
        else
          echo "main_version=$main_version" >> $GITHUB_OUTPUT
          echo "Main version $main_version is valid"
        fi

    - name: Check if feature version is greater than main version
      id: check-version-greater
      run: |
        feature_version="${{ steps.get-feature-version.outputs.feature_version }}"
        main_version="${{ steps.get-main-version.outputs.main_version }}"
        if [[ "$(printf '%s\n' "$main_version" "$feature_version" | sort -V | head -n 1)" = "$feature_version" ]]; then
          echo "Feature version is not greater than main version. Exiting."
          echo "Increase feature version to be greater than main version."
          echo "Main version is $main_version and feature version is $feature_version."
          exit 1
        else
          echo "Feature version $feature_version is greater than main version $main_version. Proceeding."
        fi