name: Pull Request Merged

on:
    pull_request: 
        branches: [ main ]
        types: [ closed ]

jobs:
    pr-merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: status
              run: |
                echo "Merged pull request"

