name: Push 

on: [ push ]

jobs: 
    pushed:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set jfrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env: 
                # JF_URL: ${{ secrets.JFROG_URL }}
                JF_URL: ${{ vars.JF_URL }}
                # JF_USER: ${{ secrets.JFROG_USER }}
                JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

            - name: Ping Jfrog
              run: |
                jf rt ping