name: Push 

on: [ push ]

jobs: 
    pushed:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set jfrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env: 
                JF_URL: ${{ vars.JF_URL }}
                JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
                JF_USER: ${{ secrets.JFROG_USER }}

            # - name: Ping Jfrog
            #   run: |
            #     jf rt ping

            - name: ping jfrog
              env: 
                JF_URL: ${{ vars.JF_URL }}
                JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
                JF_USER: ${{ secrets.JFROG_USER }}
              run: |
                curl -v -u$JF_USER:$JF_ACCESS_TOKEN  "https://hanumanbaan1.jfrog.io/artifactory/prch-config-repo-virtual/"

            - name: upload artifacts to jfrog repo
              env:
                JF_URL: ${{ vars.JF_URL }}
                JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
                JF_USER: ${{ secrets.JFROG_USER }}
              run: |
                 for file in prcm/*; do
                    curl -v -u$JF_USER:$JF_ACCESS_TOKEN -T "$file" "https://hanumanbaan1.jfrog.io/artifactory/prch-config-repo-virtual/prcm"
                 done           