name: Push 

on: [ push ]

jobs: 
    pushed:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set jfrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              with:
                version: 'latest'

            # - name: Ping Jfrog
            #   run: |
            #     jf rt ping

            #ping jfrog
            - name: ping jfrog
              env: 
                JF_URL: ${{ vars.JF_URL }}
                JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
                JF_USER: ${{ secrets.JFROG_USER }}
              run: |
                jf c add my-config --basic-auth-only --url $JF_URL --user $JF_USER --password $JF_ACCESS_TOKEN
                jf rt ping --server-id=my-config